version: 2

jobs:
  build:
    docker:
      - image: redjays/xenial:dkms-build
    working_directory: /project
    steps:
      - checkout
      - run:
          name: load keyring
          command: ./loadkey.sh
      - run:
          name: submit libvirt build
          command: ./build.sh
          no_output_timeout: 3600
